/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class AuthenticationError extends errors.SoferAIError {
    constructor() {
        super({
            message: "AuthenticationError",
            statusCode: 401,
        });
        Object.setPrototypeOf(this, AuthenticationError.prototype);
    }
}
