/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class TranscriptionNotFound extends errors.SoferAIError {
    constructor() {
        super({
            message: "TranscriptionNotFound",
            statusCode: 404,
        });
        Object.setPrototypeOf(this, TranscriptionNotFound.prototype);
    }
}
