/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class TranscriptionFailed extends errors.SoferAIError {
    constructor() {
        super({
            message: "TranscriptionFailed",
            statusCode: 400,
        });
        Object.setPrototypeOf(this, TranscriptionFailed.prototype);
    }
}
