/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const Language: core.serialization.Schema<serializers.Language.Raw, SoferaiApi.Language>;
export declare namespace Language {
    type Raw = "en" | "he";
}
