/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";

export const Language: core.serialization.Schema<serializers.Language.Raw, SoferAI.Language> = core.serialization.enum_(
    ["en", "he"]
);

export declare namespace Language {
    type Raw = "en" | "he";
}
