/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";

export const Status: core.serialization.Schema<serializers.Status.Raw, SoferAI.Status> = core.serialization.enum_([
    "RECEIVED",
    "PENDING",
    "PROCESSING",
    "COMPLETED",
    "CANCELLED",
    "FAILED",
]);

export declare namespace Status {
    type Raw = "RECEIVED" | "PENDING" | "PROCESSING" | "COMPLETED" | "CANCELLED" | "FAILED";
}
