/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const Status: core.serialization.Schema<serializers.Status.Raw, SoferaiApi.Status>;
export declare namespace Status {
    type Raw = "RECEIVED" | "PENDING" | "PROCESSING" | "COMPLETED" | "CANCELLED" | "FAILED";
}
