/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
import { Language } from "./Language";
export declare const Timestamp: core.serialization.ObjectSchema<serializers.Timestamp.Raw, SoferaiApi.Timestamp>;
export declare namespace Timestamp {
    interface Raw {
        word: string;
        punctuated_word?: string | null;
        languages?: Language.Raw[] | null;
        start: number;
        end: number;
        speaker?: string | null;
    }
}
