/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
import { TranscriptionId } from "./TranscriptionId";
import { Language } from "./Language";
import { Status } from "./Status";
export declare const TranscriptionInfo: core.serialization.ObjectSchema<
    serializers.TranscriptionInfo.Raw,
    SoferaiApi.TranscriptionInfo
>;
export declare namespace TranscriptionInfo {
    interface Raw {
        id?: TranscriptionId.Raw | null;
        user_id?: string | null;
        title?: string | null;
        created_at?: string | null;
        primary_language?: Language.Raw | null;
        lang_for_hebrew_words?: Language.Raw[] | null;
        num_speakers?: number | null;
        status?: Status.Raw | null;
        duration?: number | null;
    }
}
