/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";

export const TranscriptionId: core.serialization.Schema<serializers.TranscriptionId.Raw, SoferAI.TranscriptionId> =
    core.serialization.string();

export declare namespace TranscriptionId {
    type Raw = string;
}
