/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
import { TranscriptionInfo } from "./TranscriptionInfo";
export declare const TranscriptionRequest: core.serialization.ObjectSchema<
    serializers.TranscriptionRequest.Raw,
    SoferaiApi.TranscriptionRequest
>;
export declare namespace TranscriptionRequest {
    interface Raw {
        audio_url?: string | null;
        audio_id?: string | null;
        info: TranscriptionInfo.Raw;
    }
}
