/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";
import { Timestamp } from "./Timestamp";
import { TranscriptionInfo } from "./TranscriptionInfo";

export const Transcription: core.serialization.ObjectSchema<serializers.Transcription.Raw, SoferAI.Transcription> =
    core.serialization.object({
        text: core.serialization.string(),
        timestamps: core.serialization.list(Timestamp).optional(),
        info: TranscriptionInfo,
    });

export declare namespace Transcription {
    interface Raw {
        text: string;
        timestamps?: Timestamp.Raw[] | null;
        info: TranscriptionInfo.Raw;
    }
}
