/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";
import { TranscriptionInfo } from "./TranscriptionInfo";

export const TranscriptionRequest: core.serialization.ObjectSchema<
    serializers.TranscriptionRequest.Raw,
    SoferAI.TranscriptionRequest
> = core.serialization.object({
    audioUrl: core.serialization.property("audio_url", core.serialization.string().optional()),
    audioId: core.serialization.property("audio_id", core.serialization.string().optional()),
    info: TranscriptionInfo,
});

export declare namespace TranscriptionRequest {
    interface Raw {
        audio_url?: string | null;
        audio_id?: string | null;
        info: TranscriptionInfo.Raw;
    }
}
