/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
import { Timestamp } from "./Timestamp";
import { TranscriptionInfo } from "./TranscriptionInfo";
export declare const Transcription: core.serialization.ObjectSchema<
    serializers.Transcription.Raw,
    SoferaiApi.Transcription
>;
export declare namespace Transcription {
    interface Raw {
        text: string;
        timestamps?: Timestamp.Raw[] | null;
        info: TranscriptionInfo.Raw;
    }
}
