/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const TranscriptionId: core.serialization.Schema<
    serializers.TranscriptionId.Raw,
    SoferaiApi.TranscriptionId
>;
export declare namespace TranscriptionId {
    type Raw = string;
}
