/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class SoferAITimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, SoferAITimeoutError.prototype);
    }
}
