"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SoferaiApiTimeoutError = void 0;
class SoferaiApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, SoferaiApiTimeoutError.prototype);
    }
}
exports.SoferaiApiTimeoutError = SoferaiApiTimeoutError;
