/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class LinkNotFound extends errors.SoferAIError {
    constructor() {
        super({
            message: "LinkNotFound",
            statusCode: 404,
        });
        Object.setPrototypeOf(this, LinkNotFound.prototype);
    }
}
