/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class LinkNotSupported extends errors.SoferAIError {
    constructor() {
        super({
            message: "LinkNotSupported",
            statusCode: 400,
        });
        Object.setPrototypeOf(this, LinkNotSupported.prototype);
    }
}
