/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class LinkError extends errors.SoferAIError {
    constructor() {
        super({
            message: "LinkError",
            statusCode: 500,
        });
        Object.setPrototypeOf(this, LinkError.prototype);
    }
}
