/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Usage {
    /** ID of the user */
    id: string;
    /** Seconds remaining for the user */
    secondsRemaining: number;
    /** ID of the organization the user belongs to */
    organizationId?: string;
}
