/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type Language = "en" | "he";
export declare const Language: {
    readonly English: "en";
    readonly Hebrew: "he";
};
