"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Language = void 0;
exports.Language = {
    English: "en",
    Hebrew: "he",
};
