"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Status = void 0;
exports.Status = {
    Received: "RECEIVED",
    Pending: "PENDING",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Cancelled: "CANCELLED",
    Failed: "FAILED",
};
