/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "RECEIVED" | "PENDING" | "PROCESSING" | "COMPLETED" | "CANCELLED" | "FAILED";

export const Status = {
    Received: "RECEIVED",
    Pending: "PENDING",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Cancelled: "CANCELLED",
    Failed: "FAILED",
} as const;
