/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type Status = "RECEIVED" | "PENDING" | "PROCESSING" | "COMPLETED" | "CANCELLED" | "FAILED";
export declare const Status: {
    readonly Received: "RECEIVED";
    readonly Pending: "PENDING";
    readonly Processing: "PROCESSING";
    readonly Completed: "COMPLETED";
    readonly Cancelled: "CANCELLED";
    readonly Failed: "FAILED";
};
