/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SoferAI from "../../../index";

export interface Timestamp {
    /** Word */
    word: string;
    /** Punctuated word */
    punctuatedWord?: string;
    /** Language for the transcription that this timestamp belongs to */
    languages?: SoferAI.Language[];
    /** Start time of the timestamp */
    start: number;
    /** End time of the timestamp */
    end: number;
    /** Speaker (Pro feature) */
    speaker?: string;
}
