/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SoferAI from "../../../index";

export interface TranscriptionInfo {
    /** ID of the transcription */
    id?: SoferAI.TranscriptionId;
    /** ID of the user */
    userId?: string;
    /** Title of the transcription */
    title?: string;
    /** Date of the transcription */
    createdAt?: Date;
    /** Primary language of the audio content */
    primaryLanguage?: SoferAI.Language;
    /** Language setting for Hebrew words processing (only need to be specified if the primary language is English) */
    langForHebrewWords?: SoferAI.Language[];
    /** Expected number of speakers in the audio */
    numSpeakers?: number;
    /** Status of the transcription */
    status?: SoferAI.Status;
    /** Duration of the transcription */
    duration?: number;
}
