/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SoferAI from "../../../index";

export interface Transcription {
    /**
     * Transcription text. if the `primary_language` was English and only one `lang_for_hebrew_words` was specified,
     * this is just the English text with whatever language for the words you specified.
     * If you set multiple `lang_for_hebrew_words`,
     * this is the text with Hebrew words, with the English text in <i>Italics</i> markup.
     * If primary language is Hebrew, this is just the Hebrew text.
     */
    text: string;
    /** Timestamps for the transcription text */
    timestamps?: SoferAI.Timestamp[];
    /** Additional information about the transcription */
    info: SoferAI.TranscriptionInfo;
}
