/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SoferAI from "../../../index";

export interface TranscriptionRequest {
    /** URL to the audio file */
    audioUrl?: string;
    /** ID of the audio file (for audio in the S3 bucket, this is the postgres storage metadata id) */
    audioId?: string;
    /** Transcription parameters */
    info: SoferAI.TranscriptionInfo;
}
