/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, SoferaiApi.Usage>;
export declare namespace Usage {
    interface Raw {
        id: string;
        seconds_remaining: number;
        organization_id?: string | null;
    }
}
