/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";

export const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, SoferAI.Usage> = core.serialization.object({
    id: core.serialization.string(),
    secondsRemaining: core.serialization.property("seconds_remaining", core.serialization.number()),
    organizationId: core.serialization.property("organization_id", core.serialization.string().optional()),
});

export declare namespace Usage {
    interface Raw {
        id: string;
        seconds_remaining: number;
        organization_id?: string | null;
    }
}
