/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface LinkResponse {
    /** Title of the file */
    title: string;
    /** Download URL of the file */
    downloadUrl: string;
    /** Format of the file */
    fileFormat: string;
    /** Name of the file */
    fileName: string;
}
