/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";

export const HealthResponse: core.serialization.ObjectSchema<serializers.HealthResponse.Raw, SoferAI.HealthResponse> =
    core.serialization.object({
        status: core.serialization.string(),
    });

export declare namespace HealthResponse {
    interface Raw {
        status: string;
    }
}
