/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const HealthResponse: core.serialization.ObjectSchema<
    serializers.HealthResponse.Raw,
    SoferaiApi.HealthResponse
>;
export declare namespace HealthResponse {
    interface Raw {
        status: string;
    }
}
