/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class UserNotFound extends errors.SoferAIError {
    constructor() {
        super({
            message: "UserNotFound",
            statusCode: 404,
        });
        Object.setPrototypeOf(this, UserNotFound.prototype);
    }
}
