/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const LinkRequest: core.serialization.ObjectSchema<serializers.LinkRequest.Raw, SoferaiApi.LinkRequest>;
export declare namespace LinkRequest {
    interface Raw {
        url: string;
    }
}
