/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SoferaiApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const LinkResponse: core.serialization.ObjectSchema<
    serializers.LinkResponse.Raw,
    SoferaiApi.LinkResponse
>;
export declare namespace LinkResponse {
    interface Raw {
        title: string;
        download_url: string;
        file_format: string;
        file_name: string;
    }
}
