/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SoferAI from "../../../../api/index";
import * as core from "../../../../core";

export const LinkResponse: core.serialization.ObjectSchema<serializers.LinkResponse.Raw, SoferAI.LinkResponse> =
    core.serialization.object({
        title: core.serialization.string(),
        downloadUrl: core.serialization.property("download_url", core.serialization.string()),
        fileFormat: core.serialization.property("file_format", core.serialization.string()),
        fileName: core.serialization.property("file_name", core.serialization.string()),
    });

export declare namespace LinkResponse {
    interface Raw {
        title: string;
        download_url: string;
        file_format: string;
        file_name: string;
    }
}
