"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SoferaiApiClient = void 0;
const Client_1 = require("./api/resources/health/client/Client");
const Client_2 = require("./api/resources/link/client/Client");
const Client_3 = require("./api/resources/transcribe/client/Client");
const Client_4 = require("./api/resources/usage/client/Client");
class SoferaiApiClient {
    constructor(_options = {}) {
        this._options = _options;
    }
    get health() {
        var _a;
        return (_a = this._health) !== null && _a !== void 0 ? _a : (this._health = new Client_1.Health(this._options));
    }
    get link() {
        var _a;
        return (_a = this._link) !== null && _a !== void 0 ? _a : (this._link = new Client_2.Link(this._options));
    }
    get transcribe() {
        var _a;
        return (_a = this._transcribe) !== null && _a !== void 0
            ? _a
            : (this._transcribe = new Client_3.Transcribe(this._options));
    }
    get usage() {
        var _a;
        return (_a = this._usage) !== null && _a !== void 0 ? _a : (this._usage = new Client_4.Usage(this._options));
    }
}
exports.SoferaiApiClient = SoferaiApiClient;
