/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const SoferaiApiEnvironment: {
    readonly Production: "https://api.sofer.ai";
    readonly Staging: "https://api-staging.sofer.ai";
    readonly Development: "http://localhost:8001";
};
export declare type SoferaiApiEnvironment =
    | typeof SoferaiApiEnvironment.Production
    | typeof SoferaiApiEnvironment.Staging
    | typeof SoferaiApiEnvironment.Development;
