"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SoferaiApiEnvironment = void 0;
exports.SoferaiApiEnvironment = {
    Production: "https://api.sofer.ai",
    Staging: "https://api-staging.sofer.ai",
    Development: "http://localhost:8001",
};
