name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      - run: corepack enable

      - name: Compile
        run: yarn && yarn build

  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      - run: corepack enable

      - name: Compile
        run: yarn && yarn test    
